repositories:
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: coredns
    url: https://coredns.github.io/helm/
  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  - name: reflector
    url: https://emberstack.github.io/helm-charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: traefik
    url: https://traefik.github.io/charts

helmfiles:
  - crds-helmfile.yaml

releases:
  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    version: 3.12.2
    values: [ metrics-server.yaml ]
  - name: coredns
    namespace: kube-system
    chart: coredns/coredns
    version: 1.39.1
    values: [ coredns.yaml ]
  - name: nfs-subdir-external-provisioner
    namespace: kube-system
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    version: 4.0.18
    values: [ nfs-storage-provisioner.yaml ]
  - name: reflector
    namespace: kube-system
    chart: reflector/reflector
    version: 9.0.318
    values: [ reflector.yaml ]
  - name: cert-manager
    namespace: kube-system
    chart: jetstack/cert-manager
    version: v1.17.1
    values: [ cert-manager.yaml ]
  - name: traefik
    namespace: kube-system
    chart: traefik/traefik
    version: 34.4.1
    values: [ traefik.yaml ]
